version: '3.1'

services: 
  mysql:
    networks:
      - newnetwork
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Rootgel2000+-
      MYSQL_DATABASE: laravel
    volumes:
      - databases:/var/lib/mysql

  phpmyadmin:
    networks:
      - newnetwork
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
  
  placement:
    networks:
      - newnetwork
    container_name: placement
    build: .
    env_file: .env_prod
    restart: unless-stopped

  caddy:
    container_name: caddy
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

networks: 
  default: 
    name: newnetwork

volumes:
  databases: